routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect('login');
});

Auth::routes();

Route::middleware(['auth', 'check_access'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('departments', 'DepartmentController');
    Route::resource('leaves', 'LeaveController');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout', 'LeaveController@requestLeave')->name('leaves.leavepost');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::post('leaves_request/leaverequest', 'LeaveController@requestPost')->name('leaves.leaverequest');
    Route::patch('leaves_request/layout/{leaf}', 'LeaveController@requestUpdate')->name('leaves.leaveupdate');
    Route::delete('leaves_request/{leaf}', 'LeaveController@requestDestroy')->name('leaves.leavedestroy');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::any('leaves_request/layout/create', 'LeaveController@create')->name('leaves.leavecreate');
    Route::get('leaves_request/filter_search', 'LeaveController@search')->name('leaves.leavesearch');
    Route::get('leaves_request/filter_search/list','LeaveController@resultlist');
    Route::get('leaves_request/search','LeaveController@search_filter')->name('leaves.leaves_search_filter');
    Route::any('leaves-list', 'LeaveController@leave_list')->name('leaves.leave_list');
    Route::get('leaves-list/edit/{id}', 'LeaveController@leave_edit')->name('leaves.leave_edit');

    Route::resource('sss', 'SocialSecurityController');
    Route::resource('tax', 'TaxController');
    Route::resource('philhealth', 'PhilhealthController');
    Route::resource('pagibig', 'PagibigController');

    Route::get('pagibigs/pagibig_list', 'PagibigController@pagibig_list');

    Route::get('employees/search', 'EmployeeController@employeeSearchView');
    Route::get('employees/searchEmp', 'EmployeeController@empSearch')->name('employee.empSearch');
    Route::resource('employees', 'EmployeeController');
    Route::any('generate_paystub/{emp_id}', 'EmployeeController@generatePDF');
    Route::any('generate_payroll/{emp_id}', 'EmployeeController@generatePDF1');


    Route::resource('attendance', 'AttendanceController');

    Route::get('roles/department/{id}',[
        'uses' => 'RoleController@edit_department',
        'as' => 'role.edit_department'
    ]);

    Route::get('roles/filter/department',[
        'uses' => 'RoleController@edit_department_filter',
        'as' => 'role.edit_department_filter'
    ]);


    Route::resource('roles', 'RoleController');
    Route::post('rolesenable', 'RoleController@enable')->name('role.enable');

    Route::resource('users', 'UserController');
    Route::post('user/isenable', 'UserController@isenable')->name('user.isenable');

    Route::resource('employment-status', 'EmploymentStatusController');
    // Route::post('employees/update', 'EmployeeController@update')->name('employees.update');
    // Route::get('employees/destroy/{id}', 'EmployeeController@destroy');
    Route::any('employees_list_ajax','EmployeeController@emp_list');

    Route::any('settings','UserController@settings');
    Route::any('user/change_password','UserController@change_password');
    Route::any('user/update_email','UserController@update_email');
    Route::any('user/update_username','UserController@update_username');
    Route::any('user/update_profile','UserController@update_profile');

    Route::get('dailytime',[
        'uses' => 'AttendanceController@dailyTime',
        'as' => 'dailytime'
    ]);

    Route::post('proccessDTR',[
        'uses' => 'AttendanceController@processDTR',
        'as' => 'proccessdtr'
    ]);

    Route::post('dtr/timein',[
        'uses' => 'AttendanceController@timeIn',
        'as' => 'proccessTimein'
    ]);

    Route::post('dtr/timeout',[
        'uses' => 'AttendanceController@timeOut',
        'as' => 'proccessTimeout'
    ]);

    Route::post('dtr/uploadcsv',[
        'uses' => 'AttendanceController@uploadCsv',
        'as' => 'uploadcsv'
    ]);

    Route::resource('payroll','PayrollController');
    Route::resource('holiday', 'HolidayController');

    Route::group(['prefix'=>'payroll'], function(){
        // Route::post('/generatess','PayrollController@generate')->name('payroll.generate');
        Route::get('/summary/{billing_number}/{employee_id}','PayrollController@summary')->name('payroll.summary');
        Route::get('/filter/search/query','PayrollController@search')->name('payroll.search');
        Route::any('/filter/search/input','PayrollController@search_filter')->name('payroll.search_filter');
        Route::any('/filter/generate_pdf/{payroll_id}','PayrollController@generate_pdf')->name('payroll.generate_pdf');
        Route::any('/filter/search_view_billing_number/{payroll_id}','PayrollController@search_view_billing_number')->name('payroll.search_view_billing_number');
        Route::get('/details/{payroll_id}','PayrollController@generate_pdf');
    });
    Route::any('bulk-payroll','PayrollController@index')->name('payroll.index');
    Route::any('bulk-payroll/generate', 'PayrollController@generate')->name('payroll.generate');

    Route::get('attendances/search','AttendanceController@searchIndex')->name('search.index');

    Route::resource('payrollledger', 'PayrollLedgerController');
    Route::post('/payrollledger/generate', 'PayrollLedgerController@generate');//->name('payrollledger.generate');
    Route::resource('overtime_request', 'OvertimeRequestController');
	Route::get('overtime_requests/filter_search','OvertimeRequestController@search')->name('overtime_request.search');
	Route::get('overtime_requests/search','OvertimeRequestController@search_filter')->name('overtime_requests.search_filter');

    Route::resource('company', 'CompanyController');
    Route::group(['prefix'=>'dtr'], function(){
        Route::resource('dtr', 'DailyTimeRecordController');
        Route::get('/history',
            [
                'uses'  => 'DailyTimeRecordController@history',
                'as'    => 'dtr.history'
            ]
        );
        Route::get('/get_history',
            [
                'uses'  => 'DailyTimeRecordController@get_history',
                'as'    => 'dtr.get_history'
            ]
        );
        Route::get('/search-filter',
            [
                'uses'  => 'DailyTimeRecordController@filter',
                'as'    => 'dtr.filter'
            ]
        );
        Route::any('/filter_list',
            [
                'uses'  => 'DailyTimeRecordController@filter_list',
                'as'    => 'dtr.filter_list'
            ]
        );

        Route::get('/tardiness',
            [
                'uses'  => 'DailyTimeRecordController@tardiness',
                'as'    => 'dtr.tardiness'
            ]
        );
        Route::get('/absences',
            [
                'uses'  => 'DailyTimeRecordController@absences',
                'as'    => 'dtr.absences'
            ]
        );
        Route::any('/absence_list',
            [
                'uses'  => 'DailyTimeRecordController@absence_list',
                'as'    => 'dtr.absence_list'
            ]
        );
        Route::get('/excel_tardiness',[
                'uses'  => 'DailyTimeRecordController@excel_tardiness',
                'as'    => 'dtr.excel_tardiness'
        ]);
        Route::any('/tardiness_list',
            [
                'uses'  => 'DailyTimeRecordController@tardiness_list',
                'as'    => 'dtr.tardiness_list'
            ]
        );
        Route::get('/download_filter_export',[
                'uses'  => 'DailyTimeRecordController@download_filter_export',
                'as'    => 'dtr.download_filter_export'
        ]);
        Route::get('/download_absence_excel',[
                'uses'  => 'DailyTimeRecordController@download_absence_excel',
                'as'    => 'dtr.download_absence_excel'
        ]);

        Route::get('/download_history_report',[
            'uses'  => 'DailyTimeRecordController@download_history_report',
            'as'    => 'dtr.download_history_report'
        ]);
    });

    Route::get('attendance/search/q','AttendanceController@searchIndex')->name('attendance.search');
    Route::any('role_list_ajax','RoleController@role_list');

    Route::get('/payrollledger/getDepartment/{id}','PayrollLedgerController@getDepartment');

    Route::get('user/search_filter','UserController@search_filter')->name('user.search_filter');
    Route::post('user/create_new_password','UserController@create_new_password')->name('user.create_new_password');
    Route::post('user/{id}/deactivate_user','UserController@deactivate_user')->name('user.deactivate_user');
    Route::post('user/{id}/activate_user','UserController@activate_user')->name('user.activate_user');

    Route::get('payrollledger/preview','PayrollLedgerController@generate')->name('payrollledger.preview');

    Route::get('holidays/search_filter','HolidayController@search_filter')->name('holiday.search_filter');

    Route::get('payroll/preview/{payroll_number}', 'PayrollLedgerController@previewUpdate');
    Route::get('payroll/print/{payroll_number}', 'PayrollController@search_view_billing_number');

    Route::resource('bank', 'BankController');
    Route::any('banks_list_ajax','BankController@bank_list');
    Route::get('bank/searchBank', 'BankController@bankSearch')->name('bank.bankSearch');


});

Route::middleware('auth')->group(function () {
    Route::get('employees/card/list',function(){
        return view('employees.list');
    })->name('emp.list');

resources/views/settings/deptlist.blade.php
@extends('layouts.master')
@section('title', 'Departments')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-sm-12 grid-margin stretch-card">
      <div class="card">
          <div class="card-header">
              Department Lists
          </div>
        <div class="card-body">
          @if ($message = Session::get('success')) 
          <div class="alert alert-success" role="alert">
            <i class="mdi mdi-alert-circle"></i>
            <strong>{{ $message }}</strong>
          </div>
          @endif

          @if ($errors->any())
          <div class="alert alert-danger">
              @foreach ($errors->all() as $error)        
              <i class="mdi mdi-alert-circle"></i>
              <strong>{{ $error }}</strong>
              @endforeach
          </div>
          @endif


          <p class="card-description">
            @if(isset($editdepartment->id ))
              <h5>Edit Mode</h5>
              <form method="POST" action="{{ route('departments.update', $editdepartment->id ) }}" enctype="multipart/form-data">
              @method('PATCH')
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name"  value="{{ $editdepartment->name }}" autocomplete="off" autofocus style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-success" type="submit"><i class="mdi mdi-lead-pencil"></i>&nbsp;&nbsp;&nbsp; UPDATE &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
              
            @else
              <form method="POST" action="{{ route('departments.store') }}" autocomplete="off">
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name" autocomplete="off" autofocus style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-primary" type="submit"><i class="mdi mdi-library-plus"></i>&nbsp;&nbsp;&nbsp; ADD &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
            @endif
          
            </form>            
          </p> <!-- /card-description -->

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr><th> Name </th> <th> Action </th> </tr>
              </thead>
              <tbody>
                @foreach($departments as $department)
                <tr>
                  <td width="85%">{{ $department->name }}  </td>
                  <td>
                    <button type="button" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm" onclick="window.location.href = '{{ URL::to('departments/' . $department->id . '/edit') }}';"><i class="mdi mdi-lead-pencil"></i></button>
                  </td>
                  <td>
                    <button href="javascript:;" type="submit" data-target="#DeleteModal{{$department->id}}" class='btn btn-outline-secondary btn-rounded btn-icon' data-toggle="modal"><i class="mdi mdi-delete"></i></button>
                  </td>
                </tr>
                <!-- DELETE -->
                <div id="DeleteModal{{$department->id}}" class="modal fade text-default" role="dialog">
                    <div class="modal-dialog ">
                        <!-- Modal content-->
                        <form action="{{ route("departments.destroy",[$department->id]) }}" id="deleteForm" method="post">
                            <div class="modal-content">
                                <div class="modal-header bg-default">

                                    <h4 class="modal-title text-center">REMOVE DEPARTMENT ?</h4>
                                </div>
                                <div class="modal-body">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <p>Do you want to really remove? This request can't be removed anymore.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                                    <button type="submit" name="" class="btn btn-danger">Yes, Remove</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                @endforeach
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div><!-- /col-lg-12 -->
  </div>
</div>


<!-- CREATE -->
<div id="CreateModal" class="modal fade text-default" role="dialog">
 <div class="modal-dialog ">
   <!-- Modal content-->
   <form action="" id="deleteForm" method="post">
       <div class="modal-content">
           <div class="modal-header bg-default">
               
               <h4 class="modal-title text-center">CREATE DEPARTMENT ?</h4>
           </div>
           <div class="modal-body">
               {{ csrf_field() }}
               {{ method_field('CREATE') }}
               <p class="text-center">
                <center>
                   <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                   <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">Yes, Save</button>
               </center>
             </p>
           </div>
           <div class="modal-footer">
             
           </div>
       </div>
   </form>
 </div>
</div>

<!-- UPDATE -->
<div id="UpdateModal" class="modal fade text-default" role="dialog">
 <div class="modal-dialog ">
   <!-- Modal content-->
   <form action="" id="deleteForm" method="post">
       <div class="modal-content">
           <div class="modal-header bg-default">
               <h4 class="modal-title text-center">UPDATE DEPARTMENT ?</h4>
           </div>
           <div class="modal-body">
               {{ csrf_field() }}
               {{ method_field('PATCH') }}
               <p class="text-center">
                <center>
                   <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                   <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">Yes, Update</button>
               </center>

           </div>
           <div class="modal-footer">
             
           </div>
       </div>
   </form>
 </div>
</div>
@endsection

@section('customjs')
<script type="text/javascript">
  function deleteData(id)
  {
     var id = id;
     var url = '{{ route("departments.destroy", ":id") }}';
     url = url.replace(':id', id);
     $("#deleteForm").attr('action', url);
  }

  function formSubmit()
  {
     $("#deleteForm").submit();
  }
</script>
@endsection

resources/views/settings/emp-status.blade.php
@extends('layouts.master')
@section('title', 'Employement Status')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-sm-12 grid-margin stretch-card">
      <div class="card">
          <div class="card-header">
              Employment Status Lists
          </div>
        <div class="card-body">
          @if ($message = Session::get('success')) 
          <div class="alert alert-success" role="alert">
            <i class="mdi mdi-alert-circle"></i>
            <strong>{{ $message }}</strong>
          </div>
          @endif

          @if ($errors->any())
          <div class="alert alert-danger">
              @foreach ($errors->all() as $error)        
              <i class="mdi mdi-alert-circle"></i>
              <strong>{{ $error }}</strong>
              @endforeach
          </div>
          @endif

          <p class="card-description">
            @if(isset($row->id ))
              <h5>Edit Mode</h5>
              <form method="POST" action="{{ route('employment-status.update', $row->id ) }}" enctype="multipart/form-data">
              @method('PATCH')
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name"  value="{{ $row->name }}"  autofocus autocomplete="off" style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-success" type="submit"><i class="mdi mdi-lead-pencil"></i>&nbsp;&nbsp;&nbsp; UPDATE &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
              
            @else
              <form method="POST" action="{{ route('employment-status.store') }}" autocomplete="off">
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name" autofocus autocomplete="off" style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-primary" type="submit"><i class="mdi mdi-library-plus"></i>&nbsp;&nbsp;&nbsp; ADD &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
            @endif
          
            </form>            
          </p> <!-- /card-description -->

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr><th> Name </th> <th> Action </th> </tr>
              </thead>
              <tbody>
                @foreach($rows as $row)
                <tr>
                  <td width="85%">{{ $row->name }}  </td>
                  <td>
                    <button type="button" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm" onclick="window.location.href = '{{ URL::to('employment-status/' . $row->id . '/edit') }}';"><i class="mdi mdi-lead-pencil"></i></button>
                  </td>
                  <td>
                    <button href="javascript:;" type="submit" data-target="#DeleteModal{{ $row->id }}" class='btn btn-outline-secondary btn-rounded btn-icon' data-toggle="modal"><i class="mdi mdi-delete"></i></button>
                  </td>
                </tr>
                <div id="DeleteModal{{ $row->id }}" class="modal fade text-default" role="dialog">
                    <div class="modal-dialog ">
                        <!-- Modal content-->
                        <form action="{{ route("employment-status.destroy", [$row->id]) }}" id="deleteForm" method="post">
                            <div class="modal-content">
                                <div class="modal-header bg-default">
                                    <h4 class="modal-title text-center">REMOVE STATUS ?</h4>
                                </div>
                                <div class="modal-body">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                   <p>Do you want to really remove? This request can't be removed anymore.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                                    <button type="submit" name="" class="btn btn-danger">Yes, Remove</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                @endforeach
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div><!-- /col-lg-12 -->
  </div>

   <div class="row">
      <div class="col-md-6 offset-md-3">{!! $rows->links() !!}</div>
    </div>
</div>

@endsection

<script type="text/javascript">
function deleteData(id)
{
   var id = id;
   var url = '{{ route("employment-status.destroy", ":id") }}';
   url = url.replace(':id', id);
   $("#deleteForm").attr('action', url);
}

function formSubmit()
{
   $("#deleteForm").submit();
}
</script>

resources/views/settings/leavelist.blade.php
@extends('layouts.master')
@section('title', 'Leaves')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-sm-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-header">
          Leave Lists
        </div>
        <div class="card-body">
          @if ($message = Session::get('success')) 
          <div class="alert alert-success" role="alert">
            <i class="mdi mdi-alert-circle"></i>
            <strong>{{ $message }}</strong>
          </div>
          @endif

          @if ($errors->any())
          <div class="alert alert-danger">
              @foreach ($errors->all() as $error)        
              <i class="mdi mdi-alert-circle"></i>
              <strong>{{ $error }}</strong>
              @endforeach
          </div>
          @endif

          <p class="card-description">
            @if(isset($editleave->id ))
              <h5>Edit Mode</h5>
              <form method="POST" action="{{ route('leaves.update', $editleave->id ) }}" enctype="multipart/form-data">
              @method('PATCH')
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name"  value="{{ $editleave->name }}" autocomplete="off" autofocus onfocus="this.value = this.value;" style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-success" type="submit"><i class="mdi mdi-lead-pencil"></i>&nbsp;&nbsp;&nbsp; UPDATE &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
              
            @else
              <form method="POST" action="{{ route('leaves.store') }}" autocomplete="off">
              @csrf
              <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Name" name="name" autocomplete="off" autofocus style="text-transform: uppercase;">
                <div class="input-group-append">
                  <button class="btn btn-sm btn-primary" type="submit"><i class="mdi mdi-library-plus"></i>&nbsp;&nbsp;&nbsp; ADD &nbsp;&nbsp;&nbsp;</button>
                </div>
              </div>
            </div>
            @endif
          
            </form>            
          </p> <!-- /card-description -->

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr><th> Name </th> <th> Action </th> </tr>
              </thead>
              <tbody>
                @foreach($leaves as $leave)
                <tr>
                  <td width="85%">{{ $leave->name }}  </td>
                  <td>
                    <button type="button" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm" onclick="window.location.href = '{{ route('leaves.leave_edit', $leave->id)  }}';"><i class="mdi mdi-lead-pencil"></i></button>
                  </td>
                  <td>
                    <button href="javascript:;" type="submit" data-target="#DeleteModal{{ $leave->id }}" class='btn btn-outline-secondary btn-rounded btn-icon' data-toggle="modal"><i class="mdi mdi-delete"></i></button>
                  </td>
                </tr>
                <div id="DeleteModal{{ $leave->id }}" class="modal fade text-default" role="dialog">
                  <div class="modal-dialog ">
                    <!-- Modal content-->
                    <form action="{{ route("leaves.destroy", [$leave->id]) }}" id="deleteForm" method="post">
                      <div class="modal-content">
                        <div class="modal-header bg-default">
                          <h4 class="modal-title text-center">REMOVE STATUS ?</h4>
                        </div>
                        <div class="modal-body">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <p>Do you want to really remove? This request can't be removed anymore.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                          <button type="submit" name="" class="btn btn-danger">Yes, Remove</button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                @endforeach
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div><!-- /col-lg-12 -->
  </div>
</div>
@endsection

<script type="text/javascript">
function deleteData(id)
{
   var id = id;
   var url = '{{ route("leaves.destroy", ":id") }}';
   url = url.replace(':id', id);
   $("#deleteForm").attr('action', url);
}

function formSubmit()
{
   $("#deleteForm").submit();
}
</script>