routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect('login');
});

Auth::routes();

Route::middleware(['auth', 'check_access'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('departments', 'DepartmentController');
    Route::resource('leaves', 'LeaveController');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout', 'LeaveController@requestLeave')->name('leaves.leavepost');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::post('leaves_request/leaverequest', 'LeaveController@requestPost')->name('leaves.leaverequest');
    Route::patch('leaves_request/layout/{leaf}', 'LeaveController@requestUpdate')->name('leaves.leaveupdate');
    Route::delete('leaves_request/{leaf}', 'LeaveController@requestDestroy')->name('leaves.leavedestroy');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::any('leaves_request/layout/create', 'LeaveController@create')->name('leaves.leavecreate');
    Route::get('leaves_request/filter_search', 'LeaveController@search')->name('leaves.leavesearch');
    Route::get('leaves_request/filter_search/list','LeaveController@resultlist');
    Route::get('leaves_request/search','LeaveController@search_filter')->name('leaves.leaves_search_filter');
    Route::any('leaves-list', 'LeaveController@leave_list')->name('leaves.leave_list');
    Route::get('leaves-list/edit/{id}', 'LeaveController@leave_edit')->name('leaves.leave_edit');

    Route::resource('sss', 'SocialSecurityController');
    Route::resource('tax', 'TaxController');
    Route::resource('philhealth', 'PhilhealthController');
    Route::resource('pagibig', 'PagibigController');

    Route::get('pagibigs/pagibig_list', 'PagibigController@pagibig_list');

    Route::get('employees/search', 'EmployeeController@employeeSearchView');
    Route::get('employees/searchEmp', 'EmployeeController@empSearch')->name('employee.empSearch');
    Route::resource('employees', 'EmployeeController');
    Route::any('generate_paystub/{emp_id}', 'EmployeeController@generatePDF');
    Route::any('generate_payroll/{emp_id}', 'EmployeeController@generatePDF1');


    Route::resource('attendance', 'AttendanceController');

    Route::get('roles/department/{id}',[
        'uses' => 'RoleController@edit_department',
        'as' => 'role.edit_department'
    ]);

    Route::get('roles/filter/department',[
        'uses' => 'RoleController@edit_department_filter',
        'as' => 'role.edit_department_filter'
    ]);


    Route::resource('roles', 'RoleController');
    Route::post('rolesenable', 'RoleController@enable')->name('role.enable');

    Route::resource('users', 'UserController');
    Route::post('user/isenable', 'UserController@isenable')->name('user.isenable');

    Route::resource('employment-status', 'EmploymentStatusController');
    // Route::post('employees/update', 'EmployeeController@update')->name('employees.update');
    // Route::get('employees/destroy/{id}', 'EmployeeController@destroy');
    Route::any('employees_list_ajax','EmployeeController@emp_list');

    Route::any('settings','UserController@settings');
    Route::any('user/change_password','UserController@change_password');
    Route::any('user/update_email','UserController@update_email');
    Route::any('user/update_username','UserController@update_username');
    Route::any('user/update_profile','UserController@update_profile');

    Route::get('dailytime',[
        'uses' => 'AttendanceController@dailyTime',
        'as' => 'dailytime'
    ]);

    Route::post('proccessDTR',[
        'uses' => 'AttendanceController@processDTR',
        'as' => 'proccessdtr'
    ]);

    Route::post('dtr/timein',[
        'uses' => 'AttendanceController@timeIn',
        'as' => 'proccessTimein'
    ]);

    Route::post('dtr/timeout',[
        'uses' => 'AttendanceController@timeOut',
        'as' => 'proccessTimeout'
    ]);

    Route::post('dtr/uploadcsv',[
        'uses' => 'AttendanceController@uploadCsv',
        'as' => 'uploadcsv'
    ]);

    Route::resource('payroll','PayrollController');
    Route::resource('holiday', 'HolidayController');

    Route::group(['prefix'=>'payroll'], function(){
        // Route::post('/generatess','PayrollController@generate')->name('payroll.generate');
        Route::get('/summary/{billing_number}/{employee_id}','PayrollController@summary')->name('payroll.summary');
        Route::get('/filter/search/query','PayrollController@search')->name('payroll.search');
        Route::any('/filter/search/input','PayrollController@search_filter')->name('payroll.search_filter');
        Route::any('/filter/generate_pdf/{payroll_id}','PayrollController@generate_pdf')->name('payroll.generate_pdf');
        Route::any('/filter/search_view_billing_number/{payroll_id}','PayrollController@search_view_billing_number')->name('payroll.search_view_billing_number');
        Route::get('/details/{payroll_id}','PayrollController@generate_pdf');
    });
    Route::any('bulk-payroll','PayrollController@index')->name('payroll.index');
    Route::any('bulk-payroll/generate', 'PayrollController@generate')->name('payroll.generate');

    Route::get('attendances/search','AttendanceController@searchIndex')->name('search.index');

    Route::resource('payrollledger', 'PayrollLedgerController');
    Route::post('/payrollledger/generate', 'PayrollLedgerController@generate');//->name('payrollledger.generate');
    Route::resource('overtime_request', 'OvertimeRequestController');
	Route::get('overtime_requests/filter_search','OvertimeRequestController@search')->name('overtime_request.search');
	Route::get('overtime_requests/search','OvertimeRequestController@search_filter')->name('overtime_requests.search_filter');

    Route::resource('company', 'CompanyController');
    Route::group(['prefix'=>'dtr'], function(){
        Route::resource('dtr', 'DailyTimeRecordController');
        Route::get('/history',
            [
                'uses'  => 'DailyTimeRecordController@history',
                'as'    => 'dtr.history'
            ]
        );
        Route::get('/get_history',
            [
                'uses'  => 'DailyTimeRecordController@get_history',
                'as'    => 'dtr.get_history'
            ]
        );
        Route::get('/search-filter',
            [
                'uses'  => 'DailyTimeRecordController@filter',
                'as'    => 'dtr.filter'
            ]
        );
        Route::any('/filter_list',
            [
                'uses'  => 'DailyTimeRecordController@filter_list',
                'as'    => 'dtr.filter_list'
            ]
        );

        Route::get('/tardiness',
            [
                'uses'  => 'DailyTimeRecordController@tardiness',
                'as'    => 'dtr.tardiness'
            ]
        );
        Route::get('/absences',
            [
                'uses'  => 'DailyTimeRecordController@absences',
                'as'    => 'dtr.absences'
            ]
        );
        Route::any('/absence_list',
            [
                'uses'  => 'DailyTimeRecordController@absence_list',
                'as'    => 'dtr.absence_list'
            ]
        );
        Route::get('/excel_tardiness',[
                'uses'  => 'DailyTimeRecordController@excel_tardiness',
                'as'    => 'dtr.excel_tardiness'
        ]);
        Route::any('/tardiness_list',
            [
                'uses'  => 'DailyTimeRecordController@tardiness_list',
                'as'    => 'dtr.tardiness_list'
            ]
        );
        Route::get('/download_filter_export',[
                'uses'  => 'DailyTimeRecordController@download_filter_export',
                'as'    => 'dtr.download_filter_export'
        ]);
        Route::get('/download_absence_excel',[
                'uses'  => 'DailyTimeRecordController@download_absence_excel',
                'as'    => 'dtr.download_absence_excel'
        ]);

        Route::get('/download_history_report',[
            'uses'  => 'DailyTimeRecordController@download_history_report',
            'as'    => 'dtr.download_history_report'
        ]);
    });

    Route::get('attendance/search/q','AttendanceController@searchIndex')->name('attendance.search');
    Route::any('role_list_ajax','RoleController@role_list');

    Route::get('/payrollledger/getDepartment/{id}','PayrollLedgerController@getDepartment');

    Route::get('user/search_filter','UserController@search_filter')->name('user.search_filter');
    Route::post('user/create_new_password','UserController@create_new_password')->name('user.create_new_password');
    Route::post('user/{id}/deactivate_user','UserController@deactivate_user')->name('user.deactivate_user');
    Route::post('user/{id}/activate_user','UserController@activate_user')->name('user.activate_user');

    Route::get('payrollledger/preview','PayrollLedgerController@generate')->name('payrollledger.preview');

    Route::get('holidays/search_filter','HolidayController@search_filter')->name('holiday.search_filter');

    Route::get('payroll/preview/{payroll_number}', 'PayrollLedgerController@previewUpdate');
    Route::get('payroll/print/{payroll_number}', 'PayrollController@search_view_billing_number');

    Route::resource('bank', 'BankController');
    Route::any('banks_list_ajax','BankController@bank_list');

app/Pagibig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pagibig extends Model
{
    //
}

app/Http/Controllers/PagibigController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use App\Pagibig;
use DataTables;

class PagibigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rows = Pagibig::latest()->paginate(50);

        return view('settings.pagibig.pagibiglist',compact('rows'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
	public function pagibig_list()
	{
		$data = Pagibig::latest()->get();
		 $data_tables = Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('id', function($row){
                $url_edit = route('pagibig.edit',[$row->id]);

                return '<a href="'.$url_edit.'">'.$row->id.'</a>';
            })
            ->addIndexColumn()
            ->addColumn('monthly_compensation', function($row){
                return '₱ '.str_replace('-',' to ₱ ',$row->monthly_compensation);
            })
			->addIndexColumn()
            ->addColumn('employee_share', function($row){
                return $row->employee_share;
            })
			->addIndexColumn()
            ->addColumn('employer_share', function($row){
                return $row->employer_share;
            })
            ->addIndexColumn()
            ->addColumn('action_edit', function($row){
				$action_edit = '<button type="button" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm" onclick="window.location.href = '."'".route('pagibig.edit',[$row->id])."'".'" style="padding: 0;"><i class="mdi mdi-lead-pencil"></i></button>';             
                return $action_edit;
            })
			->addIndexColumn()
            ->addColumn('action_delete', function($row){
				$action_delete = '<button type="button" data-target="#DeleteModal" data-toggle="modal" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm btn-delete_row" data-id="'.$row->id.'" style="padding: 0;"><i class="mdi mdi-delete"></i></button>';             
                return $action_delete;
            }) 
            ->rawColumns(['id','monthly_compensation','employee_share','employer_share','action_edit', 'action_delete'])
            ->make(true);
        
        return $data_tables;
	}	
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('settings.pagibig.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!Schema::hasTable('pagibigs')) 
        {
            return redirect('pagibig')->withErrors(['field' => 'Table does not exists.']);
        }

        $request->validate([
            'ee' => 'required',
            'er' => 'required',
            'salary_min' => 'required',
            'salary_max' => 'required'
        ]);
        
        $pagibig = new Pagibig;
        $pagibig->monthly_compensation = $request->salary_min . '-' . $request->salary_max;
        $pagibig->employee_share = $request->ee;
        $pagibig->employer_share = $request->er;
        $pagibig->save();

        return redirect('pagibig')->with('success', 'Pag-Ibig was successfully created');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Pagibig::findOrFail($id);
        return view('settings.pagibig.edit',[
            'pagibig' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'ee' => 'required',
            'er' => 'required'
        ]);

        $pagibig = Pagibig::find($id);
        $pagibig->monthly_compensation = $request->salary_min . '-' . $request->salary_max;
        $pagibig->employee_share = $request->ee;
        $pagibig->employer_share = $request->er;
        $pagibig->save();

        return redirect('pagibig')->with('success', 'Pag-Ibig was successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pagibig::destroy($id);
        return redirect('pagibig')->with('success', 'Successfully Deleted'); 
    }
}

resources/views/settings/pagibig/create.blade.php
@extends('layouts.master')

@section('title', 'PAG-IBIG Table Form')

@section('content')
<div class="content-wrapper">
  <div class="card">
    <div class="card-header">Add new PAG-IBIG salary range</div>
    <div class="card-body">
      <form method="post" action="{{ route('pagibig.store') }}">
      @csrf
          <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="salary_min">Minimum Compensation Range</label>
                <input class="form-control @error('salary_min') is-invalid @enderror" id="salary_min" type="decimal" placeholder="Minimum compensation range" name="salary_min">
                @error('salary_min')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="salary_max">Maximum Compensation Range</label>
                <input class="form-control @error('salary_max') is-invalid @enderror" id="salary_max" type="decimal" placeholder="Maximum compensation range" name="salary_max">
                @error('salary_max')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="ee">Employee Share Percentage</label>
                <input class="form-control @error('ee') is-invalid @enderror" id="ee" type="number" placeholder="EE" name="ee">
                @error('ee')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="er">Employer Share Percentage</label>
                <input class="form-control @error('er') is-invalid @enderror" id="er" type="number" placeholder="ER" name="er">
                @error('er')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
          </div>
          <button class="btn btn-success float-right w-sm-100" type="submit"><i class="mdi mdi-content-save"></i> SAVE</button>
		  </form>
        </div>
      
  </div>
</div>
@endsection

resources/views/settings/pagibig/edit.blade.php
@extends('layouts.master')

@section('title', 'Update PAG-IBIG Table Form')

@section('content')
<div class="content-wrapper">
  <div class="card">
    <div class="card-header">Update PAG-IBIG salary range</div>
    <div class="card-body">
      <form method="post" action="{{ route('pagibig.update',[$pagibig->id]) }}">
      @csrf
      @method('PUT')
          <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="salary_min">Minimum Compensation Range</label>
                <input class="form-control @error('salary_min') is-invalid @enderror" id="salary_min" type="decimal" placeholder="Minimum compensation range" name="salary_min" value="{{explode('-',$pagibig->monthly_compensation)[0]}}">
                @error('salary_min')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
              <label for="salary_max">Maximum Compensation Range</label>
                <input class="form-control @error('salary_max') is-invalid @enderror" id="salary_max" type="decimal" placeholder="Maximum compensation range" name="salary_max" value="{{explode('-',$pagibig->monthly_compensation)[1]}}">
                 @error('salary_max')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="ee">Employee Share Percentage</label>
                <input class="form-control @error('ee') is-invalid @enderror" id="ee" type="number" placeholder="EE" name="ee" value="{{$pagibig->employee_share}}">
                @error('ee')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
              <div class="form-group">
                <label for="er">Employer Share Percentage</label>
                <input class="form-control @error('er') is-invalid @enderror" id="er" type="number" placeholder="ER" name="er" value="{{$pagibig->employer_share}}">
                @error('er')
                <div class="invalid-feedback">{{$message}}</div>
                @enderror
              </div>
            </div>
          </div>
          <button class="btn btn-success float-right w-sm-100" type="submit"><i class="mdi mdi-check"></i> UPDATE</button>
		   </form>
        </div>
     
  </div>
</div>
@endsection

resources/views/settings/pagibig/pagibiglist.blade.php
@extends('layouts.master')
@section('title', 'Pag Ibig')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-sm-12 grid-margin stretch-card">
      <div class="card">
      <div class="card-header">Pag Ibig 2019</div>
        <div class="card-body">
          @if ($message = Session::get('success')) 
          <div class="alert alert-success" role="alert">
            <i class="mdi mdi-alert-circle"></i>
            <strong>{{ $message }}</strong>
          </div>
          @endif

          @if ($errors->any())
          <div class="alert alert-danger">
              @foreach ($errors->all() as $error)        
              <i class="mdi mdi-alert-circle"></i>
              <strong>{{ $error }}</strong>
              @endforeach
          </div>
          @endif
			<div class="form-group">
          		<a href="{{ route('pagibig.create') }}" class="btn btn-primary w-sm-100" style="position:relative;z-index:999;"><i class="mdi mdi-plus"></i> ADD NEW PAG-IBIG</a>
			</div>	
          
			<div class="table-responsive" id="search_pag_ibig_container">
				<table class="table table-bordered" id="pag_ibig_tbl">
				  <thead>
					<tr>
					<th> ID&nbsp;</th>	
					<th> Monthly Compensation&nbsp; </th> 
					<th> Employee Share&nbsp; </th> 
					<th> Employer Share&nbsp; </th> 
					<th colspan="2"> Action&nbsp;</th>
					</tr>
				  </thead>
				</table> 	
			</div>
        </div>
      </div>
    </div><!-- /col-lg-12 -->
  </div>
</div>

<div id="DeleteModal" class="modal fade text-default" role="dialog">
 <div class="modal-dialog ">
   <!-- Modal content-->
   <form action="" id="deleteForm" method="post">
       <div class="modal-content">
           <div class="modal-header bg-default">

				<h4 class="modal-title text-center">REMOVE MONTHLY COMPENSATION?</h4>
			</div>
			<div class="modal-body">
				{{ csrf_field() }}
				{{ method_field('DELETE') }}
				<p class="delete-alert">Do you want to really remove? This request can't be removed anymore.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
				<button type="submit" name="" class="btn btn-danger">Yes, Remove</button>
			</div>
       </div>
   </form>
 </div>
</div>
@endsection

<script type="text/javascript">
function deleteData(id)
{
   var id = id;
   var url = '{{ route("pagibig.destroy", ":id") }}';
   url = url.replace(':id', id);
   $("#deleteForm").attr('action', url);
}

function formSubmit()
{
   $("#deleteForm").submit();
}


</script>
@section('customjs')
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script type="text/javascript">

var SITEURL = '{{URL::to('')}}';
 $(document).ready( function () {
    $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': '{{ csrf_token() }}'
      }
    });
    
	load_datatable();
	
 });
  function load_datatable(){
        $("#search_pag_ibig_container").show();
        $('#pag_ibig_tbl').DataTable({
            searching: false,
            processing: true,
            serverSide: true,
            responsive: true,
            autoWidth : false, 
            dom   : "<'row'<'col-sm-12 float-right margin-bottom20'B>><'row'<'col-sm-12 col-xs-12 text-right'l>><'row'<'col-sm-12'tr>><'row'<'col-sm-5 col-xs-6'i><'col-sm-7 col-xs-6'p>>",
            ajax: {
                url : "{{ url('pagibigs/pagibig_list') }}",
                type: 'GET',
                data: function (f) {
                  
                }
            },	  
            columns: [
                { data: 'id', sortable:true },
                { data: 'monthly_compensation', sortable:false },
                { data: 'employee_share', sortable:true },
                { data: 'employer_share', sortable:true },
                { data: 'action_edit', sortable:false },
                { data: 'action_delete', sortable:false }
            ],
        });
        $('#pag_ibig_tbl').on( 'error.dt', function ( e, settings, techNote, message ) {
            console.log( 'An error has been reported by DataTables: ', message );
        } ) .DataTable();
        $.fn.dataTable.ext.errMode = 'none';
        //$("#search_pag_ibig_container").hide();
      	/*if(window.matchMedia("(max-width: 992px)").matches){
            $("#search_result_container").css("margin-top", "0px");
        }else{
            $("#search_result_container").css("margin-top", "-50px");
        }*/
		
        $("#pag_ibig_tbl").on('click', '.btn-delete_row', function (){
            var id = $(this).data('id');
            var url = '{{ route("pagibig.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#DeleteModal").find('.delete-alert').html('Do you want to remove <span class="badge badge-primary">'+id+'</span> ? This overtime request can\'t be restored anymore.');
            $("#deleteForm").attr('action', url);
        });

        $("#btn-submit_delete_row").on('click', function (){
            $("#deleteForm").submit();
        });
    }

</script>
@endsection