routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect('login');
});

Auth::routes();

Route::middleware(['auth', 'check_access'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('departments', 'DepartmentController');
    Route::resource('leaves', 'LeaveController');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout', 'LeaveController@requestLeave')->name('leaves.leavepost');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::post('leaves_request/leaverequest', 'LeaveController@requestPost')->name('leaves.leaverequest');
    Route::patch('leaves_request/layout/{leaf}', 'LeaveController@requestUpdate')->name('leaves.leaveupdate');
    Route::delete('leaves_request/{leaf}', 'LeaveController@requestDestroy')->name('leaves.leavedestroy');
    Route::get('leaves_request/list', 'LeaveController@requestList')->name('leaves.leavelist');
    Route::get('leaves_request/layout/{leaf}/edit', 'LeaveController@requestEdit')->name('leaves.leaveedit');
    Route::any('leaves_request/layout/create', 'LeaveController@create')->name('leaves.leavecreate');
    Route::get('leaves_request/filter_search', 'LeaveController@search')->name('leaves.leavesearch');
    Route::get('leaves_request/filter_search/list','LeaveController@resultlist');
    Route::get('leaves_request/search','LeaveController@search_filter')->name('leaves.leaves_search_filter');
    Route::any('leaves-list', 'LeaveController@leave_list')->name('leaves.leave_list');
    Route::get('leaves-list/edit/{id}', 'LeaveController@leave_edit')->name('leaves.leave_edit');

    Route::resource('sss', 'SocialSecurityController');
    Route::resource('tax', 'TaxController');
    Route::resource('philhealth', 'PhilhealthController');
    Route::resource('pagibig', 'PagibigController');

    Route::get('pagibigs/pagibig_list', 'PagibigController@pagibig_list');

    Route::get('employees/search', 'EmployeeController@employeeSearchView');
    Route::get('employees/searchEmp', 'EmployeeController@empSearch')->name('employee.empSearch');
    Route::resource('employees', 'EmployeeController');
    Route::any('generate_paystub/{emp_id}', 'EmployeeController@generatePDF');
    Route::any('generate_payroll/{emp_id}', 'EmployeeController@generatePDF1');


    Route::resource('attendance', 'AttendanceController');

    Route::get('roles/department/{id}',[
        'uses' => 'RoleController@edit_department',
        'as' => 'role.edit_department'
    ]);

    Route::get('roles/filter/department',[
        'uses' => 'RoleController@edit_department_filter',
        'as' => 'role.edit_department_filter'
    ]);


    Route::resource('roles', 'RoleController');
    Route::post('rolesenable', 'RoleController@enable')->name('role.enable');

    Route::resource('users', 'UserController');
    Route::post('user/isenable', 'UserController@isenable')->name('user.isenable');

    Route::resource('employment-status', 'EmploymentStatusController');
    // Route::post('employees/update', 'EmployeeController@update')->name('employees.update');
    // Route::get('employees/destroy/{id}', 'EmployeeController@destroy');
    Route::any('employees_list_ajax','EmployeeController@emp_list');

    Route::any('settings','UserController@settings');
    Route::any('user/change_password','UserController@change_password');
    Route::any('user/update_email','UserController@update_email');
    Route::any('user/update_username','UserController@update_username');
    Route::any('user/update_profile','UserController@update_profile');

    Route::get('dailytime',[
        'uses' => 'AttendanceController@dailyTime',
        'as' => 'dailytime'
    ]);

    Route::post('proccessDTR',[
        'uses' => 'AttendanceController@processDTR',
        'as' => 'proccessdtr'
    ]);

    Route::post('dtr/timein',[
        'uses' => 'AttendanceController@timeIn',
        'as' => 'proccessTimein'
    ]);

    Route::post('dtr/timeout',[
        'uses' => 'AttendanceController@timeOut',
        'as' => 'proccessTimeout'
    ]);

    Route::post('dtr/uploadcsv',[
        'uses' => 'AttendanceController@uploadCsv',
        'as' => 'uploadcsv'
    ]);

    Route::resource('payroll','PayrollController');
    Route::resource('holiday', 'HolidayController');

    Route::group(['prefix'=>'payroll'], function(){
        // Route::post('/generatess','PayrollController@generate')->name('payroll.generate');
        Route::get('/summary/{billing_number}/{employee_id}','PayrollController@summary')->name('payroll.summary');
        Route::get('/filter/search/query','PayrollController@search')->name('payroll.search');
        Route::any('/filter/search/input','PayrollController@search_filter')->name('payroll.search_filter');
        Route::any('/filter/generate_pdf/{payroll_id}','PayrollController@generate_pdf')->name('payroll.generate_pdf');
        Route::any('/filter/search_view_billing_number/{payroll_id}','PayrollController@search_view_billing_number')->name('payroll.search_view_billing_number');
        Route::get('/details/{payroll_id}','PayrollController@generate_pdf');
    });
    Route::any('bulk-payroll','PayrollController@index')->name('payroll.index');
    Route::any('bulk-payroll/generate', 'PayrollController@generate')->name('payroll.generate');

    Route::get('attendances/search','AttendanceController@searchIndex')->name('search.index');

    Route::resource('payrollledger', 'PayrollLedgerController');
    Route::post('/payrollledger/generate', 'PayrollLedgerController@generate');//->name('payrollledger.generate');
    Route::resource('overtime_request', 'OvertimeRequestController');
	Route::get('overtime_requests/filter_search','OvertimeRequestController@search')->name('overtime_request.search');
	Route::get('overtime_requests/search','OvertimeRequestController@search_filter')->name('overtime_requests.search_filter');

    Route::resource('company', 'CompanyController');
    Route::group(['prefix'=>'dtr'], function(){
        Route::resource('dtr', 'DailyTimeRecordController');
        Route::get('/history',
            [
                'uses'  => 'DailyTimeRecordController@history',
                'as'    => 'dtr.history'
            ]
        );
        Route::get('/get_history',
            [
                'uses'  => 'DailyTimeRecordController@get_history',
                'as'    => 'dtr.get_history'
            ]
        );
        Route::get('/search-filter',
            [
                'uses'  => 'DailyTimeRecordController@filter',
                'as'    => 'dtr.filter'
            ]
        );
        Route::any('/filter_list',
            [
                'uses'  => 'DailyTimeRecordController@filter_list',
                'as'    => 'dtr.filter_list'
            ]
        );

        Route::get('/tardiness',
            [
                'uses'  => 'DailyTimeRecordController@tardiness',
                'as'    => 'dtr.tardiness'
            ]
        );
        Route::get('/absences',
            [
                'uses'  => 'DailyTimeRecordController@absences',
                'as'    => 'dtr.absences'
            ]
        );
        Route::any('/absence_list',
            [
                'uses'  => 'DailyTimeRecordController@absence_list',
                'as'    => 'dtr.absence_list'
            ]
        );
        Route::get('/excel_tardiness',[
                'uses'  => 'DailyTimeRecordController@excel_tardiness',
                'as'    => 'dtr.excel_tardiness'
        ]);
        Route::any('/tardiness_list',
            [
                'uses'  => 'DailyTimeRecordController@tardiness_list',
                'as'    => 'dtr.tardiness_list'
            ]
        );
        Route::get('/download_filter_export',[
                'uses'  => 'DailyTimeRecordController@download_filter_export',
                'as'    => 'dtr.download_filter_export'
        ]);
        Route::get('/download_absence_excel',[
                'uses'  => 'DailyTimeRecordController@download_absence_excel',
                'as'    => 'dtr.download_absence_excel'
        ]);

        Route::get('/download_history_report',[
            'uses'  => 'DailyTimeRecordController@download_history_report',
            'as'    => 'dtr.download_history_report'
        ]);
    });

    Route::get('attendance/search/q','AttendanceController@searchIndex')->name('attendance.search');
    Route::any('role_list_ajax','RoleController@role_list');

    Route::get('/payrollledger/getDepartment/{id}','PayrollLedgerController@getDepartment');

    Route::get('user/search_filter','UserController@search_filter')->name('user.search_filter');
    Route::post('user/create_new_password','UserController@create_new_password')->name('user.create_new_password');
    Route::post('user/{id}/deactivate_user','UserController@deactivate_user')->name('user.deactivate_user');
    Route::post('user/{id}/activate_user','UserController@activate_user')->name('user.activate_user');

    Route::get('payrollledger/preview','PayrollLedgerController@generate')->name('payrollledger.preview');

    Route::get('holidays/search_filter','HolidayController@search_filter')->name('holiday.search_filter');

    Route::get('payroll/preview/{payroll_number}', 'PayrollLedgerController@previewUpdate');
    Route::get('payroll/print/{payroll_number}', 'PayrollController@search_view_billing_number');

    Route::resource('bank', 'BankController');
    Route::any('banks_list_ajax','BankController@bank_list');

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
class Attendance extends Model
{
    /**
     * Return all generated employees from attendances
     * @return void
     */
    public function scopeEmployees($query, $date=array()) 
    {
        return $query->groupBy('employee_id')->whereBetween('date',$date)->get();
    }

    /**
     * Get the the total hours of an employee
     * @return void
     */
    public function scopeHours($query, $employee, $date=array())
    {
        return $query->select('employee_id','name', DB::raw('count(total) as total_days'))
                        ->where('employee_id',$employee)
                        ->whereBetween('date',$date)
                        ->first()->toArray();
    }

    // testing
}

resources/views/attendance/create.blade.php
@extends('layouts.master')
@section('title', 'Attendance')
@section('content')
<div class="content-wrapper">
    <div class="content">
        <div class="container-fluid">
        @include('includes.messages')
            <div class="card">
                <div class="card-header">
                    Upload Attendance CSV Format
                </div>
                <div class="card-body">
                @error('csv')
                        <div class="alert alert-danger">
                            {{$message}}
                        </div>
                @enderror
                <form class="form-inline" method="post" action="{{ route('uploadcsv') }}" enctype="multipart/form-data">
                @csrf
                    <div class="form-group mx-sm-3 mb-2">
                        <input type="file" name="csv" class="form-control-file is-invalid" id="inputfile">
                    </div>
                    <button type="submit" class="btn btn-success mb-2 w-sm-100">Upload</button>
                    </form>
                    
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-header">
                    Add Attendance Record
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('attendance.store') }}"
                    aria-label="{{ __('Attendance') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="date">Date:</label>
                            <input type="date" class="form-control @error('date') is-invalid @enderror" id="date" name="date" value="{{ old('date') }}">
                            @error('date')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                        </div>
                        @if(Auth::user()->employee_id == '1')
                            <div class="form-group">
                                <label for="name">Employee name:</label>
                                <select class="form-control  @error('name') is-invalid @enderror" name="name" id="name">
                                    <option value="">-Select Employee-</option>
                                    @foreach($employees as $employee)
                                        <option value="{{ $employee->id }}">{{ ucwords($employee->first_name) }} {{ ucwords($employee->last_name) }}</option>
                                    @endforeach
                                </select>
                                @error('name')
                                <div class="invalid-feedback">{{$message}}</div>
                                @enderror
                            </div>
                        @else
                            <input type="hidden" class="form-control" id="name" placeholder="Enter Employee" name="name"
                                    value="{{ Auth::user()->employee_id }}">
                        @endif
                        

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="time_in">Time in:</label>
                                    <input type="time" class="form-control  @error('time_in') is-invalid @enderror" id="time_in" name="time_in"
                                        value="{{ old('time_in') }}">
                                    @error('time_in')
                                    <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group ">
                                    <label for="time_out">Time out:</label>
                                    <input type="time" class="form-control @error('time_out') is-invalid @enderror" id="time_out" name="time_out"
                                        value="{{ old('time_out') }}">
                                    @error('time_out')
                                    <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-check form-check-flat form-check-primary">
                          <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" name="night_shift">
                            Night Shift
                          <i class="input-helper"></i></label><p><small class="help-block">Check if the current record is for night shift. It will add +1 day on timeout.</small></p>
                        </div> 
						<div class="text-right">
                        <button type="submit" class="btn btn-success full-width-xs"><i class="fa fa-save"> </i> SAVE</button>
						</div>	
                    </div>
                    <!-- /.box-body -->
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/attendance/edit.blade.php
@extends('layouts.master')
@section('title', 'Attendance')
@section('content')
<div class="content-wrapper">
    <div class="content">
        <div class="container-fluid">
        @include('includes.messages')
            <div class="card">
                <div class="card-header">
                    Update Attendance Record
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('attendance.update',[$record->id]) }}"
                    aria-label="{{ __('Attendance') }}">
                    @method('PUT')
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="date">Date:</label>
                            <input type="date" class="form-control @error('date') is-invalid @enderror" id="date" name="date" value="{{ $record->date }}">
                            @error('date')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                        </div>
                        @if(Auth::user()->employee_id == '1')
                            <div class="form-group">
                                <label for="name">Employee name:</label>
                                <select class="form-control  @error('name') is-invalid @enderror" name="name" id="name">
                                    <option value="">-Select Employee-</option>
                                    @foreach($employees as $employee)
                                        <option @if($employee->id == $record->employee_id) selected @endif value="{{ $employee->id }}">{{ ucwords($employee->first_name) }} {{ ucwords($employee->last_name) }}</option>
                                    @endforeach
                                </select>
                                @error('name')
                                <div class="invalid-feedback">{{$message}}</div>
                                @enderror
                            </div>
                        @else
                            <input type="hidden" class="form-control" id="name" placeholder="Enter Employee" name="name"
                                    value="{{ Auth::user()->employee_id }}">
                        @endif
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="time_in">Time in:</label>
                                    <input type="time" class="form-control  @error('time_in') is-invalid @enderror" id="time_in" name="time_in"
                                        value="{{ date('H:i', strtotime($record->time_in)) }}">
                                    @error('time_in')
                                    <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group ">
                                    <label for="time_out">Time out:</label>
                                    <input type="time" class="form-control @error('time_out') is-invalid @enderror" id="time_out" name="time_out"
                                        value="{{ date('H:i', strtotime($record->time_out)) }}">
                                    @error('time_out')
                                    <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
						
						 <div class="form-check form-check-flat form-check-primary">
                          <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" name="night_shift" {{$record->night_shift == true ? __('checked'):__('')}} >
                            Night Shift
                          <i class="input-helper"></i></label><p><small class="help-block">Check if the current record is for night shift. It will add +1 day on timeout.</small></p>
                        </div> 
						
                        <div class="text-right">
                            <button type="submit" class="btn btn-success full-width-xs mt-1"><i class="fas fa-save"></i> UPDATE</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/attendance/search.blade.php
@extends('layouts.master')
@section('title', 'Attendance')
@section('content')
<div class="content-wrapper">
    <div class="content">
<<<<<<< HEAD
=======
        <div class="">
>>>>>>> 1a6e60fb929c41b86f85ce36456264c406097f3c
            @include('includes.messages')
            <div class="card mb-2">
                <div class="card-header">Attendance</div>
                <div class="card-body">
				<div class="row">
				  <div class="col-md-3 col-sm-4 col-xs-12">
					<a class="btn btn-block btn-primary btn-icon-text btn-sm" href="{{ route ('attendance.create') }}"><i class="mdi mdi-plus"></i> Add New Record</a>  
				  </div>
				</div>
				<br />
                <form method="GET" action="{{ route ('attendance.search') }}">
                    @if(Auth::user()->employee_id == '1')
                    <div class="form-group">
                        <select class="form-control" name="name[]" id="select2_names" multiple style="max-height: 200px;">
                          @foreach($employees as $employee)
                              <option 
                                @if(request()->has('name')) 
                                    @if(in_array($employee->id, request('name')))
                                        selected
                                    @endif
                                @endif
                                value="{{$employee->id}}"
                              >
                              {{ ucwords($employee->first_name) }} {{ ucwords($employee->last_name) }}
                              </option>
                          @endforeach
                      </select>
                    </div>
                    @else
                      <input class="form-control" type="hidden" name="name[]" value="{{ ucwords($current_employee->id) }}">
                    @endif
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="from_date">From</label>
                              <input class="form-control" type="date" id="from_date" name="from_date" value="{{ request()->has('from_date') ? request()->get('from_date') : '' }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="from_date">To</label>
                              <input class="form-control" type="date" id="to_date" name="to_date" value="{{ request()->has('to_date') ? request()->get('to_date') : '' }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-md-10"></div>
                      
                      <div class="col-md-2">
                        <div class="form-group">
                            <button type="submit" id="searchEmployee" class="btn btn-block btn-primary btn-icon-text btn-sm w-sm-100">
                                <i class="mdi mdi-account-search"></i>                                                    
                                Search
                            </button>
                        </div> 
                      </div>
                    </div>
                    </form>
                </div>
            </div> 
            <!-- /card -->
            <!-- <div class="row">
              <div class="col-lg-12">
                <div class="d-flex float-right">
                  <div class="p-2">
                    <form method="post" action="{{ route('proccessTimein') }}">
                      @csrf
                      <button type="submit" class="btn btn-success">TIME-IN</button>
                    </form>
                  </div>
                  <div class="p-2"><button class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">TIME-OUT</button></div>
                </div>
              </div>
            </div> -->
            
            <div class="card">
                <div class="card-header">Attendance records</div>
                <div class="card-body">
					<div class="table-responsive" >
                    @if($record)
                    <table class="table" id="attendance_tabl">
                        <thead>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Time-In</th>
                            <th>Time-Out</th>
                            <th>Total</th>
                            <th>Last Updated</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                          @foreach($record as $r)
                            <tr>                           
                              <td>{{ $r->date}} @if($r->night_shift == true)<small><span class="badge badge-dark">night</span></small>@endif</td>
                              <td>{{ $r->name}}</td>
                              <td>{{ date('H:i', strtotime($r->time_in)) }} <abbr title="{{ date('h:i a @ D M-j-Y', strtotime($r->time_in)) }}"><small><em>{{ date('Y-m-d', strtotime($r->time_in))}}</em></small></abbr></td>
                              <td>
                              @if(strlen($r->time_out)!=1)
                              {{ date('H:i', strtotime($r->time_out))}} <abbr title="{{ date('h:i a @ D M-j-Y', strtotime($r->time_out)) }}"><small><em>{{ date('Y-m-d', strtotime($r->time_out))}}</em></small></abbr>
                              @else
                              --:-- 
                              @endif
                              </td>
                              <td>
                                <?php
                                  $time_in = strtotime($r->time_in);
                                  $time_out = strtotime($r->time_out);
                                  $total_time = $time_out - $time_in;

                                  echo ($r->time_out=='-')?'00:00:00' :gmdate("H:i:s", $total_time);
                                ?>
                              </td>
                              <td>
                                @if($r->updated_at)
                                  {{date('Y-m-d', strtotime($r->updated_at))}}
                                @endif
                              </td>
                              <td>
                                <div class="row col-lg">
                                  <div class="col">
                                    <button type="button" class="btn btn-outline-secondary btn-rounded btn-icon btn-sm" onclick="window.location.href = '{{ route('attendance.edit', [$r->id]) }}';"><i class="mdi mdi-lead-pencil"></i></button>
                                  </div>
                                  <div class="col">
                                    <button type="submit" class='btn btn-outline-secondary btn-rounded btn-icon' data-toggle="modal" data-target="#modal-{{$r->id}}"><i class="mdi mdi-delete"></i></button>
                                  </div>
                                </div>
                              </td>
                            </tr>
                            <div class="modal fade" id="modal-{{$r->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalCenterTitle">Are you sure?</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                  Delete record <span class="badge badge-primary">{{$r->date}}</span> ? This can't be undone.
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary d-sm-block w-sm-100" data-dismiss="modal">Close</button>
                                  <form action="{{ route('attendance.destroy', [$r->id]) }}" method="post">
                                    @method('DELETE')
                                    @csrf
                                  <button type="submit" class="btn btn-danger d-sm-block w-sm-100">Delete</button>
                                  </form>
                                </div>
                              </div>
                            </div>
                          </div>
                          @endforeach
                        </tbody>
                        @else 
                        <div class="alert alert-warning">There are no records as of the moment</div>
                        @endif
                    </table>
                    @if($record)
                        {!! $record->appends(Request::except('page'))->render() !!}
                    @endif
					</div>	
                </div>
            </div>
    </div>
</div>
<!-- Modal -->
<div class="modal" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm Timeout?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       Are you sure. You want to Time-out ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{{ route('proccessTimeout') }}">
        @csrf
        <input type="hidden" value="{{ Session::get('attendance_id') }}" name="att_id">
        <button type="submit" class="btn btn-danger">TIMEOUT</button>
        </form>
      </div>
    </div>
  </div>
</div>



@endsection

@section('javascript')
<!-- OPTIONAL SCRIPTS -->
<script src="/dist/plugins/chart.js/Chart.min.js"></script>
<script src="/dist/js/demo.js"></script>
<script src="/dist/js/pages/dashboard3.js"></script>


<!-- DataTables -->
<script src="/dist/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables/dataTables.bootstrap4.js"></script>
@endsection